In [1]:
import pandas as pd
import matplotlib as plt
%matplotlib inline
import numpy as np

In [2]:
all_train_data = pd.read_csv("c:/Users/Rachel/Documents/Grad_Stuff/Dissertation/final_train_data_legens.csv")

In [3]:
all_train_data

file   ID  language       start questions  \
0     p254p255-part1_ch2  255   English    5.889176        WH   
1     p254p255-part1_ch2  255   English   26.446841       Y/N   
2     p254p255-part1_ch2  255   English   30.233468        WH   
3     p254p255-part1_ch2  255   English   48.636714        WH   
4     p254p255-part1_ch2  255   English  104.758627        WH   
5     p254p255-part1_ch2  255   English  118.306289       Y/N   
6     p254p255-part1_ch2  255   English  142.635380       Y/N   
7     p254p255-part1_ch2  255   English  152.205946       Y/N   
8     p254p255-part1_ch2  255   English  211.408755       Y/N   
9     p254p255-part1_ch2  255   English  284.433922        WH   
10    p254p255-part1_ch2  255   English  290.516178        WH   
11    p254p255-part1_ch2  255   English  305.194943        WH   
12    p254p255-part1_ch2  255   English  308.530373       Y/N   
13    p254p255-part1_ch2  255   English  363.860604       Y/N   
14    p254p255-part1_ch2  255   English  370.603639        WH   
15    p254p255-part1_ch2  255   English  381.585251       Y/N   
16    p254p255-part1_ch2  255   English  416.171533       Y/N   
17    p254p255-part1_ch2  255   English  434.355349       Y/N   
18    p254p255-part1_ch2  255   English  444.158805       Y/N   
19    p254p255-part1_ch2  255   English  450.868906       Y/N   
20    p254p255-part1_ch2  255   English  463.436278        WH   
21    p254p255-part1_ch2  255   English  543.697132        WH   
22    p254p255-part1_ch2  255   English  602.585570       Y/N   
23    p254p255-part1_ch2  255   English  647.653809       Y/N   
24    p254p255-part1_ch2  255   English  700.244484        WH   
25    p254p255-part1_ch2  255   English  759.700644       Y/N   
26    p254p255-part1_ch2  255   English  763.762020       Y/N   
27    p254p255-part1_ch2  255   English  862.826277        WH   
28    p254p255-part1_ch2  255   English  910.405556       Y/N   
29    p254p255-part1_ch2  255   English  916.984339        WH   
...                  ...  ...       ...         ...       ...   
1764  p382p383-part2_ch1  383  Mandarin  455.979525       Y/N   
1765  p382p383-part2_ch1  383  Mandarin  481.321037        WH   
1766  p382p383-part2_ch1  383  Mandarin  497.560971       Y/N   
1767  p382p383-part2_ch1  383  Mandarin  506.072285        WH   
1768  p382p383-part2_ch1  383  Mandarin  520.783765        WH   
1769  p382p383-part2_ch1  383  Mandarin  530.841253        WH   
1770  p382p383-part2_ch1  383  Mandarin  556.440336        WH   
1771  p382p383-part2_ch1  383  Mandarin  571.725112        WH   
1772  p382p383-part2_ch1  383  Mandarin  576.769203        WH   
1773  p382p383-part2_ch1  383  Mandarin  613.999652       Y/N   
1774  p382p383-part2_ch1  383  Mandarin  631.548903       Y/N   
1775  p382p383-part2_ch1  383  Mandarin  636.883512        WH   
1776  p382p383-part2_ch1  383  Mandarin  638.192829        WH   
1777  p382p383-part2_ch1  383  Mandarin  646.038752        WH   
1778  p382p383-part2_ch1  383  Mandarin  657.029933        WH   
1779  p382p383-part2_ch1  383  Mandarin  678.435256       Y/N   
1780  p382p383-part2_ch1  383  Mandarin  716.152392        WH   
1781  p382p383-part2_ch1  383  Mandarin  726.682093        WH   
1782  p382p383-part2_ch1  383  Mandarin  735.204889       Y/N   
1783  p382p383-part2_ch1  383  Mandarin  746.560962        WH   
1784  p382p383-part2_ch1  383  Mandarin  765.882260       Y/N   
1785  p382p383-part2_ch1  383  Mandarin  814.118364        WH   
1786  p382p383-part2_ch1  383  Mandarin  861.839328        WH   
1787  p382p383-part2_ch1  383  Mandarin  873.774936        WH   
1788  p382p383-part2_ch1  383  Mandarin  941.588661        WH   
1789  p382p383-part2_ch1  383  Mandarin  951.088079        WH   
1790  p382p383-part2_ch1  383  Mandarin  962.830508        WH   
1791  p382p383-part2_ch1  383  Mandarin  971.824766       Y/N   
1792  p382p383-part2_ch1  383  Mandarin  977.800807        WH   
1793  p382p383-part2_ch1  383  Mandarin  997.496480    

In [3]:
all_f0s = []
for i, row in all_train_data.iterrows():
    f0s = np.fromstring(row["f0final"][2:-2], dtype=float, sep="\n")
    #print (type((f0s)))
    all_f0s.append(f0s)

    #leges = np.fromstring(row["legen_coefs"][1:-1], dtype=float, sep=",")
    #coeffs.append(leges)

In [5]:
all_f0s[0]

array([   0.     ,    0.     ,   50.64992,   65.85841,   81.4403 ,
         98.20233,   99.75562,  100.1022 ,   98.18985,   95.55511,
         93.37106,   92.19338,   92.12261,   92.88293,   94.12119,
         95.73397,   97.78253,  100.3587 ,  103.193  ,  106.1362 ,
        108.9988 ,  111.8998 ,  114.8152 ,  117.7447 ,  120.6446 ,
        123.6656 ,  127.3163 ,  131.9924 ,  137.48   ,  142.7894 ,
        147.3857 ,  151.6205 ,  155.4733 ,  158.6302 ,  160.537  ,
        161.5594 ,  161.9183 ,  161.7408 ,  161.0598 ,  160.0973 ,
        158.9817 ,  157.822  ,  156.6525 ,  155.463  ,  154.2142 ,
        152.7217 ,  150.9617 ,  149.0664 ,  147.2113 ,  145.6245 ,
        144.3863 ,  143.692  ,  143.5844 ,  144.0273 ,  144.8118 ,
        145.7382 ,  146.7216 ,  147.826  ,  149.1426 ,  150.49   ,
        151.7324 ,  152.7168 ,  153.561  ,  154.276  ,  155.0011 ,
        155.7691 ,  155.45   ,  153.7246 ,  151.1536 ,  149.4974 ,
        149.4962 ,  150.3382 ,  151.1872 ,  151.5352 ,  151.56

In [4]:
maxf0s = []
#minf0s = []
for listf0s in all_f0s:
    high = max(listf0s)
    #low = min(listf0s)
    maxf0s.append(high)
    #minf0s.append(low)

 

In [5]:
minf0s = []
interlist = []
for listf0s in all_f0s:
    for item in listf0s:
        if item == 0:
            pass
        else:
            interlist.append(item)
    low = min(interlist)
    minf0s.append(low)
    interlist = []

In [6]:
print (len(minf0s))

1794


In [9]:
print(minf0s[:10])

[50.649920000000002, 48.827289999999998, 46.543880000000001, 47.565689999999996, 54.749319999999997, 47.705080000000002, 60.298580000000001, 46.044559999999997, 80.070499999999996, 44.107610000000001]


In [7]:
rangef0s = []
for i in range(len(maxf0s)):
    diff = maxf0s[i] - minf0s[i]
    rangef0s.append(diff)
print (len(rangef0s))

1794


In [8]:
dfFeatures = pd.DataFrame({'maxf0s': maxf0s, 'minf0s':minf0s, 'rangef0s':rangef0s})
#dfFeatures = pd.DataFrame({'maxf0s': maxf0s})

In [13]:
dfFeatures

maxf0s     minf0s   rangef0s
0     167.4064   50.64992  116.75648
1     161.2738   48.82729  112.44651
2     137.7850   46.54388   91.24112
3     180.0493   47.56569  132.48361
4     155.7785   54.74932  101.02918
5     129.9454   47.70508   82.24032
6     172.9097   60.29858  112.61112
7     151.8860   46.04456  105.84144
8     221.6296   80.07050  141.55910
9     145.8232   44.10761  101.71559
10    202.1402   50.50938  151.63082
11    212.2462   86.92239  125.32381
12    115.6137   95.73916   19.87454
13    246.1183   62.00704  184.11126
14    160.9482   55.80040  105.14780
15    336.3057   54.75948  281.54622
16    137.2336   53.94426   83.28934
17    305.2844   47.47062  257.81378
18    120.6686   77.66718   43.00142
19    274.2808   68.85609  205.42471
20    103.4385   54.33425   49.10425
21    185.0264   43.52264  141.50376
22    512.4105   67.01822  445.39228
23    175.3600   45.93912  129.42088
24    210.6993   56.00160  154.69770
25    198.5315   47.04184  151.48966
26    191.4276   75.85903  115.56857
27    276.4906   43.41079  233.07981
28    161.2224   88.13658   73.08582
29    146.0019   59.29282   86.70908
...        ...        ...        ...
1764  260.4405   46.06943  214.37107
1765  225.8414   53.36279  172.47861
1766  255.4602   45.49388  209.96632
1767  227.4445   49.41138  178.03312
1768  255.8540   45.11232  210.74168
1769  224.1410   70.82341  153.31759
1770  252.2016   57.46036  194.74124
1771  250.1336   45.14540  204.98820
1772  201.6432   51.24586  150.39734
1773  294.9699   50.55550  244.41440
1774  250.4057   43.30656  207.09914
1775  234.5705   62.78240  171.78810
1776  212.0153   57.51490  154.50040
1777  266.2784   96.12913  170.14927
1778  255.9491   47.99936  207.94974
1779  273.3046   69.98690  203.31770
1780  246.6184   45.87569  200.74271
1781  270.7204   46.62912  224.09128
1782  210.5926   66.10973  144.48287
1783  284.8203   43.18724  241.63306
1784  267.1701   44.32131  222.84879
1785  231.3675   43.95663  187.41087
1786  256.0181  172.26330   83.75480
1787  228.8418   65.05637  163.78543
1788  240.6431   93.43084  147.21226
1789  222.7558   61.26596  161.48984
1790  230.5302   46.63869  183.89151
1791  599.3553   43.90968  555.44562
1792  228.9018   92.59078  136.31102
1793  272.2958  161.89630  110.39950

[1794 rows x 3 columns]

In [9]:
#get labels
df_labels = pd.DataFrame(all_train_data[['language','questions']])


In [30]:
#for language or question labels only
#df_labels = pd.DataFrame(all_train_data['language'])

In [78]:
#df_labels = pd.DataFrame({'labels':dfFeatures['language'] + " " + dfFeatures['questions']})

KeyError: 'language'

In [10]:
#to combine language and questions into a single label
df_labels = pd.DataFrame({'labels':df_labels['language'] + " " + df_labels['questions']})

In [70]:
### do not need this - no reason for it to make these into a full dataframe right now
#dfFeatures[['language', 'questions']] = all_train_data[['language', 'questions']]

In [11]:
df_labels

labels
0       English WH
1      English Y/N
2       English WH
3       English WH
4       English WH
5      English Y/N
6      English Y/N
7      English Y/N
8      English Y/N
9       English WH
10      English WH
11      English WH
12     English Y/N
13     English Y/N
14      English WH
15     English Y/N
16     English Y/N
17     English Y/N
18     English Y/N
19     English Y/N
20      English WH
21      English WH
22     English Y/N
23     English Y/N
24      English WH
25     English Y/N
26     English Y/N
27      English WH
28     English Y/N
29      English WH
...            ...
1764  Mandarin Y/N
1765   Mandarin WH
1766  Mandarin Y/N
1767   Mandarin WH
1768   Mandarin WH
1769   Mandarin WH
1770   Mandarin WH
1771   Mandarin WH
1772   Mandarin WH
1773  Mandarin Y/N
1774  Mandarin Y/N
1775   Mandarin WH
1776   Mandarin WH
1777   Mandarin WH
1778   Mandarin WH
1779  Mandarin Y/N
1780   Mandarin WH
1781   Mandarin WH
1782  Mandarin Y/N
1783   Mandarin WH
1784  Mandarin Y/N
1785   Mandarin WH
1786   Mandarin WH
1787   Mandarin WH
1788   Mandarin WH
1789   Mandarin WH
1790   Mandarin WH
1791  Mandarin Y/N
1792   Mandarin WH
1793   Mandarin WH

[1794 rows x 1 columns]

In [69]:
#not needed, here for observation purposes
#df_coeff_sorted = df_coeff.groupby(['language', 'questions'])

In [10]:
#df_labels = pd.DataFrame({'labels':df_coeff['language'] + " " + df_coeff['questions']})

In [11]:
#keeping this here for observation purposes
#df_data = df_coeff.drop(['language', 'questions'], axis=1)

In [12]:
df_labels.values.squeeze()

array(['English WH', 'English Y/N', 'English WH', ..., 'Mandarin Y/N',
       'Mandarin WH', 'Mandarin WH'], dtype=object)

In [13]:
import sklearn

In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import svm
from sklearn import dummy

In [33]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
#cv = ShuffleSplit(n_splits=2, test_size=0.3, random_state=0)

In [42]:
scores = cross_val_score(clf, dfFeatures, df_labels.values.squeeze(), cv=10)
#scores = cross_val_score(clf, dfFeatures, df_labels.values(), cv=10)

In [43]:
scores

array([ 0.29120879,  0.29281768,  0.20441989,  0.29050279,  0.20670391,
        0.29050279,  0.27374302,  0.29213483,  0.29213483,  0.31460674])

In [21]:
cross_val_score?

### Calculate a majority baseline (stratified baseline?) so we know how well the classifier is doing

http://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html

In [15]:
from sklearn.dummy import DummyClassifier
dclf = DummyClassifier()

In [17]:
baseline_scores = cross_val_score(dclf, dfFeatures, df_labels.values.squeeze(), cv=10)

In [18]:
baseline_scores

array([ 0.32417582,  0.25414365,  0.33701657,  0.25139665,  0.2122905 ,
        0.19553073,  0.20670391,  0.24157303,  0.23033708,  0.24157303])