In [1]:
import pandas as pd
import matplotlib as plt
%matplotlib inline
import numpy as np

In [3]:
all_train_probs = pd.read_csv("c:/Users/Rachel/Documents/Grad_Stuff/Dissertation/degree_trials_data/final_probs_7deg.csv")

In [ ]:
all_train_probs

In [5]:
all_train_data = pd.read_csv("c:/Users/Rachel/Documents/Grad_Stuff/Dissertation/degree_trials_data/degree7_train_normspkrmean_legens.csv")

In [ ]:
all_train_data

In [6]:
all_train_probs = all_train_probs.rename(index=float, columns={"English: WH": "EnglishWH", "English: Y/N":"EnglishYN","Mandarin: WH": "MandarinWH", "Mandarin: Y/N":'MandarinYN'})

In [7]:
prob_features = all_train_probs.drop(["id", "language","questions"], axis=1)

In [8]:
prob_features

EnglishWH     EnglishYN    MandarinWH    MandarinYN
0.0     1.415565e-15  9.523445e-16  1.001217e-15  8.760393e-16
1.0     1.387464e-15  1.573747e-15  1.299808e-15  2.286458e-15
2.0     1.227084e-15  1.622860e-15  1.830458e-15  3.636998e-15
3.0     2.196436e-15  2.406798e-15  1.940409e-15  3.160343e-15
4.0     1.293424e-15  1.682207e-15  1.442955e-15  4.061333e-15
5.0     2.223825e-15  2.025025e-15  1.730717e-15  2.104687e-15
6.0     2.891158e-15  2.215113e-15  1.890581e-15  2.314640e-15
7.0     8.361176e-16  3.260600e-16  2.733269e-16  1.673705e-16
8.0     7.770796e-16  8.348154e-16  1.056386e-15  2.084295e-15
9.0     1.793793e-15  1.484600e-15  1.716381e-15  1.826471e-15
10.0    2.636826e-15  3.332439e-15  2.643300e-15  4.653303e-15
11.0    1.172937e-16  6.714183e-17  5.017959e-17  9.434456e-18
12.0    2.317229e-16  1.020945e-16  1.182784e-16  6.219484e-17
13.0    4.334279e-17  1.112305e-16  6.276484e-17  8.400527e-17
14.0    1.308530e-15  9.971466e-16  8.360774e-16  8.739390e-16
15.0    3.375297e-15  3.053371e-15  2.637828e-15  3.711222e-15
16.0    1.966590e-15  2.397758e-15  2.066653e-15  3.737091e-15
17.0    1.548023e-16  8.205960e-17  4.692893e-17  2.070952e-17
18.0    1.018356e-15  4.414289e-16  9.448041e-16  8.496894e-16
19.0    1.809927e-15  1.921860e-15  1.483090e-15  2.286568e-15
20.0    2.694548e-15  1.717238e-15  2.018733e-15  2.733012e-15
21.0    3.360169e-15  2.792652e-15  2.877146e-15  4.975255e-15
22.0    1.741807e-16  1.717331e-16  1.301610e-16  8.085996e-17
23.0    9.722265e-16  7.088232e-16  7.089529e-16  4.285777e-16
24.0    1.792797e-16  7.031620e-17  1.478888e-16  9.042652e-17
25.0    1.384635e-15  1.543409e-15  1.286113e-15  2.677083e-15
26.0    3.031421e-16  7.481169e-16  4.804579e-16  6.649492e-16
27.0    8.519525e-18  3.639883e-18  8.215287e-18  4.575582e-18
28.0    7.047172e-16  1.003351e-15  5.182477e-16  4.304793e-16
29.0    2.115868e-15  1.710893e-15  1.462309e-15  1.924704e-15
...              ...           ...           ...           ...
1374.0  9.288889e-16  1.121154e-15  7.878768e-16  1.564450e-15
1375.0  1.695136e-15  1.644009e-15  1.537556e-15  2.725274e-15
1376.0  3.024771e-15  2.486045e-15  1.770339e-15  1.909062e-15
1377.0  5.021227e-17  8.061227e-17  9.178498e-17  1.992696e-16
1378.0  7.092757e-16  4.229706e-16  7.082813e-16  7.451664e-16
1379.0  2.841500e-15  2.647317e-15  2.752146e-15  5.294446e-15
1380.0  2.744385e-15  2.718389e-15  1.685766e-15  3.306741e-15
1381.0  1.548848e-15  1.880053e-15  1.922758e-15  4.537623e-15
1382.0  2.460660e-15  1.615559e-15  2.145087e-15  3.172353e-15
1383.0  2.033048e-15  1.676953e-15  8.975311e-16  1.088409e-15
1384.0  3.010955e-15  3.479535e-15  3.392611e-15  8.443760e-15
1385.0  1.598818e-15  1.321894e-15  2.029010e-15  3.286523e-15
1386.0  1.570284e-15  1.561540e-15  1.140573e-15  1.459843e-15
1387.0  2.209657e-15  2.736186e-15  2.399761e-15  4.588884e-15
1388.0  2.516124e-15  2.256494e-15  2.344452e-15  4.282014e-15
1389.0  6.141739e-16  7.277745e-16  7.410657e-16  1.899924e-15
1390.0  1.153130e-15  1.101246e-15  1.841854e-15  3.029539e-15
1391.0  2.197344e-15  1.557152e-15  2.317293e-15  3.381934e-15
1392.0  2.472807e-15  1.471612e-15  2.192799e-15  2.930233e-15
1393.0  1.966633e-16  3.076231e-16  1.829061e-16  4.773739e-16
1394.0  8.940373e-16  4.390079e-16  8.824422e-16  1.081732e-15
1395.0  1.485462e-15  1.126954e-15  1.992075e-15  3.087473e-15
1396.0  4.781509e-16  7.328334e-16  5.422532e-16  1.228520e-15
1397.0  1.129663e-16  8.731695e-17  1.488133e-16  1.005047e-16
1398.0  2.558104e-16  4.282564e-16  3.513937e-16  1.036994e-15
1399.0  5.126230e-16  6.287357e-16  6.540713e-16  1.607827e-15
1400.0  2.605160e-16  3.286989e-16  2.017023e-16  2.364722e-16
1401.0  5.082807e-16  8.288241e-16  4.197258e-16  1.144735e-15
1402.0  8.797795e-16  9.428284e-16  6.702967e-16  1.402665e-15
1403.0  2.220405e-15  2.083714e-15  2.712119e-15  5.455975e-15

[1404 rows x 4 columns]

In [9]:
all_train_data = pd.concat([all_train_data, prob_features], axis=1)

In [ ]:
all_train_data

In [ ]:
# coeffs = []
# EngWH = []
# EngYN = []
# ManWH = []
# ManYN = []
# for i, row in all_train_data.iterrows():
#     leges = np.fromstring(row["legen_coefs"][1:-1], dtype=float, sep=",")
#     enwhs = np.fromstring(row["EnglishWH"][1:-1], dtype=float, sep=",")
#     enyn = np.fromstring(row["EnglishY/N"][1:-1], dtype=float, sep=",")
#     manwhs = np.fromstring(row["MandarinWH"][1:-1], dtype=float, sep=",")
#     manyn = np.fromstring(row["MandarinY/N"][1:-1], dtype=float, sep=",")
#     coeffs.append(leges)
#     EngWH.append(enwhs)
#     EngYN.append(enyn)
#     ManWH.append(manwhs)
#     ManYN.append(manyn)

In [ ]:
coeffs = []

for i, row in all_train_data.iterrows():
    #print (row["legen_coefs"])
    leges = np.fromstring(row["legen_coefs"][1:-1], dtype=float, sep=",")
    coeffs.append(leges)


In [11]:
coeffs = []

for i, row in all_train_data.iterrows():
    leges = np.fromstring(row["legen_coefs"][1:-1], dtype=float, sep=",")
    coeffs.append(leges)


In [12]:
coeffs

[array([ 25.92665833, -28.762645  , -78.1014576 ,   2.29642951,
        -32.24577399,  -4.19642931,   9.64255481]),
 array([ 26.75340654,  27.10238131, -24.17565717,  34.96478099,
        -27.59544995,  28.45267231, -29.90804409]),
 array([ -5.33721246, -45.2911419 ,  16.07377829,  19.9477399 ,
        -30.39594165, -19.54688176, -37.07405999]),
 array([ -4.0788067 ,  23.19950604,   0.51064185,  28.09994571,
        -22.4089839 ,  -4.1398797 ,  15.77282318]),
 array([ 12.75824692, -28.09191088,  -6.08091242,  34.37315353,
        -10.44843189,  21.83693315, -77.291415  ]),
 array([ -7.48632953,  14.86786812, -40.12085442,  -7.64105994,
        -70.81856363,  -1.40956754,  19.04650647]),
 array([ -8.85840468, -31.19375575, -47.31092117,  45.39367545,
        -28.29403996, -16.02344466,  16.59404238]),
 array([-17.44298704, -10.60743509, -83.77548584,   2.8297457 ,
        -40.77878177,  30.99678522,  70.45039035]),
 array([ 12.52653008,   3.65730297,  -8.84768757, -27.75633906,
        

In [ ]:
[[f'lg_{n}' for n in range(7)]]

In [13]:
####CHANGE DEGREE####range(x)where x is degree
df_coeff = pd.DataFrame(coeffs, columns = [f'lg{n}' for n in range(7)])

In [ ]:
df_coeff

In [ ]:
all_train_data['legen_coefs']

In [ ]:
all_train_data

In [14]:
df_coeff[['language', 'questions']] = all_train_data[['language', 'questions']]

In [ ]:
df_coeff

In [15]:
df_coeff = pd.concat([df_coeff, prob_features], axis=1)

In [ ]:
df_coeff

In [ ]:
df_coeff_sorted = df_coeff.groupby(['language', 'questions'])

In [ ]:
df_coeff_sorted.groups

In [ ]:
df_coeff.columns

In [16]:
df_labels = pd.DataFrame({'labels':df_coeff['language'] + " " + df_coeff['questions']})

In [ ]:
df_labels

In [17]:
df_data = df_coeff.drop(['language', 'questions'], axis=1)

In [ ]:
df_data

In [18]:
import sklearn

In [19]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import svm
from sklearn import dummy

In [20]:
from sklearn.dummy import DummyClassifier
dclf = DummyClassifier()

In [21]:
baseline_scores = cross_val_score(dclf, df_data, df_labels.values.squeeze(), cv=10)
baseline_scores.mean()

0.2352596073842487

In [22]:
from sklearn.cross_validation import train_test_split
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression

#clf= LogisticRegression()

#cv = ShuffleSplit(n_splits=2, test_size=0.3, random_state=0)

C:\Users\Rachel\AppData\Local\Continuum\Anaconda2\envs\py36\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


### Let's do some motherfuckin' GridSearching of parameters

In [23]:
## NOTE: grid_search is depreciating, will change to model_selection module
#param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
#              'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}



param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}

from sklearn.grid_search import GridSearchCV
#from sklearn.svm import SVC
grid_search = GridSearchCV(LinearSVC(), param_grid, cv=10)

X_train, X_test, y_train, y_test = train_test_split(df_data, df_labels.values.squeeze(), random_state=0)

grid_search.fit(X_train, y_train)

print(grid_search.best_params_)
print(grid_search.best_score_)

C:\Users\Rachel\AppData\Local\Continuum\Anaconda2\envs\py36\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


{'C': 0.001}
0.33903133903133903


In [ ]:
Not working
# X_train, X_test, y_train, y_test = train_test_split(df_data, df_labels, random_state=0)
# dclf.fit(X_train, y_train)
# basescore = dclf.score(X_test, y_test)
# print(basescore)

In [ ]:
print('The scikit-learn version is {}.'.format(sklearn.__version__))

In [24]:
clf = LinearSVC(C=0.001)
scores = cross_val_score(clf, df_data, df_labels.values.squeeze(), cv=10)

In [25]:
scores.mean()

0.3345540196715702

In [ ]:
cross_val_score?

In [26]:
#### BETTER THAN CROSS VALIDATION DONE THE OTHER WAY ##########
X_train, X_test, y_train, y_test = train_test_split(df_data, df_labels, random_state=0)

#logreg = LogisticRegression().fit(X_train, y_train)
#score = logreg.score(X_test, y_test)

#classifier = linear_model.LogisticRegression()
classifier = svm.LinearSVC(C=0.001)
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
predicts = classifier.predict(X_test)

print (score, predicts)

C:\Users\Rachel\AppData\Local\Continuum\Anaconda2\envs\py36\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.358974358974359 ['English WH' 'English WH' 'English WH' 'Mandarin Y/N' 'Mandarin Y/N'
 'English WH' 'English WH' 'English WH' 'Mandarin WH' 'English Y/N'
 'Mandarin WH' 'English WH' 'Mandarin Y/N' 'Mandarin WH' 'English WH'
 'Mandarin Y/N' 'English WH' 'Mandarin WH' 'Mandarin WH' 'Mandarin WH'
 'Mandarin Y/N' 'Mandarin WH' 'Mandarin WH' 'English WH' 'English WH'
 'English Y/N' 'Mandarin WH' 'English WH' 'English Y/N' 'English WH'
 'Mandarin Y/N' 'Mandarin WH' 'English WH' 'English Y/N' 'Mandarin WH'
 'Mandarin Y/N' 'English WH' 'Mandarin WH' 'English WH' 'Mandarin WH'
 'English WH' 'English WH' 'English WH' 'English WH' 'English WH'
 'Mandarin WH' 'Mandarin Y/N' 'English WH' 'Mandarin WH' 'Mandarin WH'
 'English WH' 'Mandarin WH' 'Mandarin WH' 'English Y/N' 'English WH'
 'English WH' 'Mandarin Y/N' 'English WH' 'Mandarin WH' 'Mandarin WH'
 'Mandarin WH' 'English WH' 'English WH' 'English WH' 'English WH'
 'English WH' 'English Y/N' 'Mandarin WH' 'English WH' 'English WH'
 'Mandarin W

In [ ]:
df_coeff['label'] = df_labels

In [ ]:
import matplotlib.pyplot as plt
fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(15,5))
df_coeff.groupby('label').mean().T.plot.bar(ax=ax1)
df_coeff.groupby('label').std().T.plot.bar(ax=ax2)

In [ ]:
fig, ax = plt.subplots(figsize=(20,10))
_ = df_coeff.boxplot(by = 'label', ax=ax, layout = (2,4))

In [ ]:
import seaborn as sns

In [ ]:
fig, ax= plt.subplots(nrows=2, ncols=4, figsize=(20,10))
axlist = ax.flatten()
for i, l in enumerate(df_coeff.columns[0:7]):
    _ = sns.boxplot(x="label", y=l, data=df_coeff, ax=axlist[i])